name: First Workflow
env:
    MY_VAR: "Hello, World!"
on:
    workflow_dispatch:
    issues:
        types: [opened]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Step 1
              run: echo "Step 1 complete!"
            - name: Echo Step 2
              run: echo ${{ env.MY_VAR }}

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: Cowsays
              uses: mscoutermarsh/cowsays-action@master
              with:
                  text: ${{ env.MY_VAR }}
                  color: 'magenta'
